version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysqlService
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=nodejs
      - MYSQL_USER=useruser
      - MYSQL_PASSWORD=admin
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
